// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXsOS6GU0RcybyDdjuSWoIjtPS4R5w_AE',
    appId: '1:1086086624317:ios:b4fed829569aa4b0702654',
    messagingSenderId: '1086086624317',
    projectId: 'gastoclub',
    storageBucket: 'gastoclub.firebasestorage.app',
    iosClientId: '1086086624317-jolccd7ot3a0ljbvbs8jj5l6o3q32ef4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastoclub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtHLqyyorlS50-iEI9fmVzRQRpM32mHag',
    appId: '1:1086086624317:web:395fb1b367d3c86c702654',
    messagingSenderId: '1086086624317',
    projectId: 'gastoclub',
    authDomain: 'gastoclub.firebaseapp.com',
    storageBucket: 'gastoclub.firebasestorage.app',
    measurementId: 'G-8DK6M1RZZM',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHLqyyorlS50-iEI9fmVzRQRpM32mHag',
    appId: '1:1086086624317:web:395fb1b367d3c86c702654',
    messagingSenderId: '1086086624317',
    projectId: 'gastoclub',
    authDomain: 'gastoclub.firebaseapp.com',
    storageBucket: 'gastoclub.firebasestorage.app',
    measurementId: 'G-8DK6M1RZZM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXsOS6GU0RcybyDdjuSWoIjtPS4R5w_AE',
    appId: '1:1086086624317:ios:b4fed829569aa4b0702654',
    messagingSenderId: '1086086624317',
    projectId: 'gastoclub',
    storageBucket: 'gastoclub.firebasestorage.app',
    iosClientId: '1086086624317-jolccd7ot3a0ljbvbs8jj5l6o3q32ef4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gastoclub',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mPL3dS30VN8BBSH1Po13nsa8MROfIss',
    appId: '1:1086086624317:android:8522d5efab571f6c702654',
    messagingSenderId: '1086086624317',
    projectId: 'gastoclub',
    storageBucket: 'gastoclub.firebasestorage.app',
  );

}